---
title: "explore_project2"
author: "Candice MH"
date: "Sunday, November 09, 2014"
output: html_document
---

The author acknowledges the data source for this project from <http://www.epa.gov/ttn/chief/eiinformation.html>.

library(data.table)
library(ggplot2)
setwd("~/GitHub/Explore_Project2")

NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
NEI<-data.table(NEI)
SCC<-data.table(SCC)

##Have total emissions from PM2.5 decreased in the United States from 1999 to 2008? Using the base plotting system, make a plot showing the total PM2.5 emission from all sources for each of the years 1999, 2002, 2005, and 2008.
png(filename = "plot1.png", width = 480, height = 480, units = "px")
yearSum<-NEI[, lapply(.SD, sum, na.rm=TRUE), by=year, .SDcols=c("Emissions")] 
plot(yearSum,xlab="Year",main="Total emissions from 1999 to 2008")
dev.off()

##Have total emissions from PM2.5 decreased in the Baltimore City, Maryland (fips == "24510") from 1999 to 2008? Use the base plotting system to make a plot answering this question.
png(filename = "plot2.png", width = 480, height = 480, units = "px")
yearSum2<-NEI[fips == "24510", lapply(.SD, sum, na.rm=TRUE), by=year, .SDcols=c("Emissions")] 
plot(yearSum2,xlab="Year",main="Total emissions from 1999 to 2008 \n Baltimore City, Maryland")
dev.off()

##Of the four types of sources indicated by the type (point, nonpoint, onroad, nonroad) variable, which of these four sources have seen decreases in emissions from 1999-2008 for Baltimore City? Which have seen increases in emissions from 1999-2008? Use the ggplot2 plotting system to make a plot answer this question.
png(filename = "plot3.png", width = 480, height = 480, units = "px")
yeartypeSum3<-NEI[fips == "24510", lapply(.SD, sum, na.rm=TRUE), by=c("year","type"), .SDcols=c("Emissions")] 
qplot(year, Emissions, data=yeartypeSum3, geom=c("point", "smooth"), color=type, main="Total emissions from 1999 to 2008 \n in Baltimore City, Maryland, \n by type of source.", xlab="Year", ylab="Emissions")
dev.off()

##Across the United States, how have emissions from coal combustion-related sources changed from 1999-2008?
png(filename = "plot4.png", width = 480, height = 480, units = "px")
SCCcoal<-SCC$SCC[grepl("Coal",SCC$EI.Sector)]
yearSum4<-NEI[NEI$SCC %in% SCCcoal, lapply(.SD, sum, na.rm=TRUE), by=c("year"), .SDcols=c("Emissions")] 
qplot(year, Emissions, data=yearSum4, geom=c("point","smooth"), main="Total emissions from 1999 to 2008 \n from coal combustion-related sources.", xlab="Year", ylab="Emissions")
dev.off()

##How have emissions from motor vehicle sources changed from 1999-2008 in Baltimore City?
png(filename = "plot5.png", width = 480, height = 480, units = "px")
SCCmv<-SCC$SCC[grepl("Onroad",SCC$Data.Category)]
yearSum5<-NEI[which(is.element(NEI$fips, 24510) & is.element(NEI$SCC, SCCmv)), lapply(.SD, sum, na.rm=TRUE), by=c("year"), .SDcols=c("Emissions")] 
qplot(year, Emissions, data=yearSum5, geom=c("point","smooth"), main="Total emissions from 1999 to 2008 \n from motor vehicle sources in Baltimore City.", xlab="Year", ylab="Emissions")
dev.off()

##Compare emissions from motor vehicle sources in Baltimore City with emissions from motor vehicle sources in Los Angeles County, California (fips == "06037"). Which city has seen greater changes over time in motor vehicle emissions?
png(filename = "plot6.png", width = 480, height = 480, units = "px")
yearSum6<-NEI[which(NEI$fips %in% c("24510","06037") & is.element(NEI$SCC, SCCmv)), lapply(.SD, sum, na.rm=TRUE), by=c("year","fips"), .SDcols=c("Emissions")] 
qplot(year, Emissions, data=yearSum6, geom=c("point", "smooth"), color=fips, main="Total emissions from motor vehicle sources from 1999 to 2008 in\n Baltimore City (24510) and Los Angeles County (06037).", xlab="Year", ylab="Emissions")
dev.off()